language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-basic-page' ]; then cd .. && eval "mv $currentfolder generator-basic-page" && cd generator-basic-page; fi
